# Numerical Python (NumPy)

Allows to work on multidimensional array

Website: [NumPy](https://numpy.org)



### Install numpy library

In [4]:
! pip install numpy 

### Importing library in the notebook

In [5]:
import numpy as np # Way to import the numpy library 

### Convering a list into a numpy array

In [6]:
myList = [1,2,3]
myArray = np.array(myList)

print('myArray',myArray)

print('Type of myArray',type(myArray))

myArray [1 2 3]
Type of myArray <class 'numpy.ndarray'>


### Multidimensional arrays

In [7]:
list_of_lists = np.array([[1,2,4],[4,6,7]])

print('Shape',list_of_lists.shape)

Shape (2, 3)


### Creating Range

In [8]:
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

Range with intervals

In [9]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### Generate array with zeros

In [10]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### A three by three array of ones

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Diagonally one

In [12]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Reshaping the array (Change dimensions)

* The multiplication of dimensions should be equal to the number of elements in array. 
* The orignal array is retained



In [13]:
mn = np.arange(0,50)

mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### Resizing the array

* Changes the orignal array

In [14]:
o = np.arange(0,50)
o.resize(10,5)
o

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### Return evenly spaced values in a range

In [15]:
np.linspace(0,7,5)

array([0.  , 1.75, 3.5 , 5.25, 7.  ])

### Generate random numbers between 0 & 1

* The arguments should provide the dimensions for array
* Returns numbers from uniform distribution

In [16]:
np.random.rand(3,2)

array([[0.76553778, 0.29191328],
       [0.37607993, 0.53541071],
       [0.46573453, 0.8247619 ]])

#### Return random numbers from standard normal distribution

In [17]:
np.random.randn(3,2)

array([[-0.52817818, -0.26661227],
       [ 1.25756702,  1.02702894],
       [-0.76983935, -1.15031371]])

#### Return random integers from low(inclusive) and high (exclusive)

In [18]:
np.random.randint(4,15,10) # generate 10 random numbers between 4 and 15

array([ 4,  6,  7,  5,  5, 11, 11,  9,  4,  6])

## Indexing and Slicing

In [19]:
 mn = np.random.randint(4,15,100)
 print('Array',mn)
 print('Index 1',mn[1])
 print('Negative Index',mn[-4])
 print('Range',mn[3:6])
 print('Range from',mn[3:])
 print('Negative index in range',mn[3:-2])

Array [ 9 14 13  9  9  6  8  9  6  5  6  6  5 10 13  8  5  7  9  4 14 12  8 10
  7 14  7 13 10 13 12 14 14  5  6  6  4 10 13 13  6  8  8  8 13 13  6  6
 13  9  5 12 11  7  8 11  6  7 10  9 13 10 10  4 11  4 13  7  4 11 12  9
 10 10 12  4 11 13 13 12  5  8  4  6 13 11 14  6  5  7  4 10 14  7  5  7
  7 14 11  8]
Index 1 14
Negative Index 7
Range [9 9 6]
Range from [ 9  9  6  8  9  6  5  6  6  5 10 13  8  5  7  9  4 14 12  8 10  7 14  7
 13 10 13 12 14 14  5  6  6  4 10 13 13  6  8  8  8 13 13  6  6 13  9  5
 12 11  7  8 11  6  7 10  9 13 10 10  4 11  4 13  7  4 11 12  9 10 10 12
  4 11 13 13 12  5  8  4  6 13 11 14  6  5  7  4 10 14  7  5  7  7 14 11
  8]
Negative index in range [ 9  9  6  8  9  6  5  6  6  5 10 13  8  5  7  9  4 14 12  8 10  7 14  7
 13 10 13 12 14 14  5  6  6  4 10 13 13  6  8  8  8 13 13  6  6 13  9  5
 12 11  7  8 11  6  7 10  9 13 10 10  4 11  4 13  7  4 11 12  9 10 10 12
  4 11 13 13 12  5  8  4  6 13 11 14  6  5  7  4 10 14  7  5  7  7 14]


#### Indexing for multidimensional array

In [20]:
mn.resize(10,10)
print(mn)
print(mn[5,7])

[[ 9 14 13  9  9  6  8  9  6  5]
 [ 6  6  5 10 13  8  5  7  9  4]
 [14 12  8 10  7 14  7 13 10 13]
 [12 14 14  5  6  6  4 10 13 13]
 [ 6  8  8  8 13 13  6  6 13  9]
 [ 5 12 11  7  8 11  6  7 10  9]
 [13 10 10  4 11  4 13  7  4 11]
 [12  9 10 10 12  4 11 13 13 12]
 [ 5  8  4  6 13 11 14  6  5  7]
 [ 4 10 14  7  5  7  7 14 11  8]]
7


#### Slicing

In [21]:
mn[3:,3:]

array([[ 5,  6,  6,  4, 10, 13, 13],
       [ 8, 13, 13,  6,  6, 13,  9],
       [ 7,  8, 11,  6,  7, 10,  9],
       [ 4, 11,  4, 13,  7,  4, 11],
       [10, 12,  4, 11, 13, 13, 12],
       [ 6, 13, 11, 14,  6,  5,  7],
       [ 7,  5,  7,  7, 14, 11,  8]])

#### Conditional Indexing

In [22]:
mn[ mn > 8 ]

array([ 9, 14, 13,  9,  9,  9, 10, 13,  9, 14, 12, 10, 14, 13, 10, 13, 12,
       14, 14, 10, 13, 13, 13, 13, 13,  9, 12, 11, 11, 10,  9, 13, 10, 10,
       11, 13, 11, 12,  9, 10, 10, 12, 11, 13, 13, 12, 13, 11, 14, 10, 14,
       14, 11])

#### Casting

Cast all values to 10 where values are greater than 10

In [23]:
mn [ mn > 10 ]=10
mn

array([[ 9, 10, 10,  9,  9,  6,  8,  9,  6,  5],
       [ 6,  6,  5, 10, 10,  8,  5,  7,  9,  4],
       [10, 10,  8, 10,  7, 10,  7, 10, 10, 10],
       [10, 10, 10,  5,  6,  6,  4, 10, 10, 10],
       [ 6,  8,  8,  8, 10, 10,  6,  6, 10,  9],
       [ 5, 10, 10,  7,  8, 10,  6,  7, 10,  9],
       [10, 10, 10,  4, 10,  4, 10,  7,  4, 10],
       [10,  9, 10, 10, 10,  4, 10, 10, 10, 10],
       [ 5,  8,  4,  6, 10, 10, 10,  6,  5,  7],
       [ 4, 10, 10,  7,  5,  7,  7, 10, 10,  8]])

#### Copy

In [24]:
mm_copy = mn.copy()
mm_copy

array([[ 9, 10, 10,  9,  9,  6,  8,  9,  6,  5],
       [ 6,  6,  5, 10, 10,  8,  5,  7,  9,  4],
       [10, 10,  8, 10,  7, 10,  7, 10, 10, 10],
       [10, 10, 10,  5,  6,  6,  4, 10, 10, 10],
       [ 6,  8,  8,  8, 10, 10,  6,  6, 10,  9],
       [ 5, 10, 10,  7,  8, 10,  6,  7, 10,  9],
       [10, 10, 10,  4, 10,  4, 10,  7,  4, 10],
       [10,  9, 10, 10, 10,  4, 10, 10, 10, 10],
       [ 5,  8,  4,  6, 10, 10, 10,  6,  5,  7],
       [ 4, 10, 10,  7,  5,  7,  7, 10, 10,  8]])

#### Mean of the array

In [25]:
mn.mean()

8.08

#### Standard Deviation

In [26]:
mn.std()

2.1103554203024664

#### Variance

In [27]:
mn.var()

4.4536

#### Array Difference

In [28]:
ab = np.arange(15,40)
cd = np.arange(10,25)
np.setdiff1d(cd,ab)

array([10, 11, 12, 13, 14])

#### Filtering an array

An array can be easily filterd by passing the conditiom as follows

In [29]:
a = np.arange(1,20)
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])