# Numerical Python (NumPy)

Allows to work on multidimensional array

Website: [NumPy](https://numpy.org)



### Install numpy library

In [ ]:
! pip install numpy 

### Importing library in the notebook

In [ ]:
import numpy as np # Way to import the numpy library 

### Convering a list into a numpy array

In [ ]:
myList = [1,2,3]
myArray = np.array(myList)

print('myArray',myArray)

print('Type of myArray',type(myArray))

myArray [1 2 3]
Type of myArray <class 'numpy.ndarray'>


### Multidimensional arrays

In [ ]:
list_of_lists = np.array([[1,2,4],[4,6,7]])

print('Shape',list_of_lists.shape)

Shape (2, 3)


### Creating Range

In [ ]:
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

Range with intervals

In [ ]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### Generate array with zeros

In [ ]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### A three by three array of ones

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Diagonally one

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Reshaping the array (Change dimensions)

* The multiplication of dimensions should be equal to the number of elements in array. 
* The orignal array is retained



In [ ]:
mn = np.arange(0,50)

mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### Resizing the array

* Changes the orignal array

In [ ]:
o = np.arange(0,50)
o.resize(10,5)
o

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### Return evenly spaced values in a range

In [ ]:
np.linspace(0,7,5)

array([0.  , 1.75, 3.5 , 5.25, 7.  ])

### Generate random numbers between 0 & 1

* The arguments should provide the dimensions for array
* Returns numbers from uniform distribution

In [ ]:
np.random.rand(3,2)

array([[0.672147  , 0.20104477],
       [0.33984072, 0.74450758],
       [0.98861337, 0.2473649 ]])

#### Return random numbers from standard normal distribution

In [ ]:
np.random.randn(3,2)

array([[-1.17026719,  0.00649464],
       [-0.71203465,  0.48072499],
       [-0.57141432, -0.03048345]])

#### Return random integers from low(inclusive) and high (exclusive)

In [ ]:
np.random.randint(4,15,10) # generate 10 random numbers between 4 and 15

array([14,  8,  9,  8,  9,  6,  8, 13,  4,  8])

# Indexing and Slicing

In [ ]:
 mn = np.random.randint(4,15,10)
 print('Array',mn)
 print('Index 1',mn[1])
 print('Negative Index',mn[-4])
 print('Range',mn[3:6])
 print('Range from',mn[3:])
 print('Negative index in range',mn[3:-2])

Array [10  5  6 11  6  9 13 10  4  4]
Index 1 5
Negative Index 13
Range [11  6  9]
Range from [11  6  9 13 10  4  4]
Negative index in range [11  6  9 13 10]


In [ ]:
mn

array([10,  5,  6, 11,  6,  9, 13, 10,  4,  4])